import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar.component";
import { Providers } from "./providers/providers";
import "@splidejs/react-splide/css";
import { LocationSection } from "./sections/location.section";
import { FooterSection } from "./sections/footer.section";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  types: string;
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body className={`${inter.className} antialiased`}>
          {children}
          <Navbar />
        </body>
      </Providers>
    </html>
  );
}
